export const preferencesAndStatsSchemas = {
	Preferences: {
		type: 'object',
		required: [
			'userId',
			'theme',
			'fontFamily',
			'textSize',
			'density',
			'defaultSort',
			'hideRead',
			'keyboardShortcutsEnabled',
			'autoMarkReadMode',
			'accentColor',
			'createdAt',
			'updatedAt',
		],
		properties: {
			userId: { type: 'string', format: 'uuid' },
			theme: { type: 'string' },
			fontFamily: { type: 'string' },
			textSize: { type: 'integer' },
			density: { type: 'string' },
			defaultSort: { type: 'string' },
			hideRead: { type: 'boolean' },
			keyboardShortcutsEnabled: { type: 'boolean' },
			autoMarkReadMode: { type: 'string' },
			accentColor: { type: ['string', 'null'] },
			createdAt: { type: 'string', format: 'date-time' },
			updatedAt: { type: 'string', format: 'date-time' },
		},
	},
	Stats: {
		type: 'object',
		required: [
			'totalUnread',
			'totalRead',
			'totalFeeds',
			'totalCategories',
			'recentSyncRuns',
			'dailyMetrics',
		],
		properties: {
			totalUnread: { type: 'integer' },
			totalRead: { type: 'integer' },
			totalFeeds: { type: 'integer' },
			totalCategories: { type: 'integer' },
			recentSyncRuns: { type: 'array', items: { $ref: '#/components/schemas/SyncRun' } },
			dailyMetrics: { type: 'array', items: { type: 'object' } },
		},
	},
	SyncRun: {
		type: 'object',
		required: [
			'id',
			'feedId',
			'feedTitle',
			'startedAt',
			'finishedAt',
			'status',
			'httpStatus',
			'itemCount',
			'errorMessage',
		],
		properties: {
			id: { type: 'string', format: 'uuid' },
			feedId: { type: 'string', format: 'uuid' },
			feedTitle: { type: ['string', 'null'] },
			startedAt: { type: 'string', format: 'date-time' },
			finishedAt: { type: ['string', 'null'], format: 'date-time' },
			status: { type: 'string', enum: ['running', 'success', 'failed'] },
			httpStatus: { type: ['integer', 'null'] },
			itemCount: { type: 'integer' },
			errorMessage: { type: ['string', 'null'], maxLength: 500 },
		},
	},
} as const;
